# Use the official Node.js image
FROM node:18

RUN npm i nodemon -g
RUN npm i ts-node -g
# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./ 

# Install application dependencies
RUN npm install

RUN npm ci


# Copy the rest of the application code
COPY . .

# Expose the port on which your Node.js app will run
EXPOSE 3500

# Command to run the application
CMD ["npm", "start"]
